# 4.2 Pseudorandom Number Generation

In [2]:
import numpy as np

samples = np.random.standard_normal(size=(4, 4))
samples

array([[ 0.79665049,  0.18098091,  2.00882266, -0.8469376 ],
       [ 1.61460237, -0.43719237,  1.69698893, -0.70300293],
       [-1.37630404, -1.53917305, -0.13942458,  0.33759515],
       [ 0.11799655,  1.42937819,  1.48641746,  0.99813833]])

In [4]:
from random import normalvariate

N = 1_000_000

%timeit samples = [normalvariate(0, 1) for _ in range(N)]

2.2 s ± 21.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [6]:
%timeit np.random.standard_normal(N)

65.1 ms ± 734 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
rng = np.random.default_rng(seed=12345)
data = rng.standard_normal((2, 3))

In [8]:
type(rng)

numpy.random._generator.Generator

<table>
    <thead>
        <th>Method</th>
        <th>Description</th>
    </thead>
    <tbody>
        <tr>
            <td>permutation</td>
            <td>Return a random permutation of a sequence, or return a permuted range</td>
        </tr>
        <tr>
            <td>shuffle</td>
            <td>Randomly permute a sequence in place</td>
        </tr>
        <tr>
            <td>uniform</td>
            <td>Draw samples from a uniform distribution</td>
        </tr>
        <tr>
            <td>integers</td>
            <td>Draw random integers from a given low-to-high range</td>
        </tr>
        <tr>
            <td>standard_normal</td>
            <td>Draw samples from a normal distribution with mean 0 and standard deviation 1 </td>
        </tr>
        <tr>
            <td>binomial</td>
            <td>Draw samples from a binomial distribution</td>
        </tr>
        <tr>
            <td>normal</td>
            <td>Draw samples from a normal (Gaussian) distribution</td>
        </tr>
        <tr>
            <td>beta</td>
            <td>Draw samples from a beta distribution</td>
        </tr>
        <tr>
            <td>chisquare</td>
            <td>Draw samples from a chi-square distribution</td>
        </tr>
        <tr>
            <td>gamma</td>
            <td>Draw samples from a gamma distribution</td>
        </tr>
        <tr>
            <td>uniform</td>
            <td>Draw samples from a uniform [0, 1) distribution</td>
        </tr>
    </tbody>
</table>

In [31]:
np.random.permutation([1, 2, 3, 4, 5]) # shuffle my list

array([1, 2, 3, 4, 5])

In [34]:
np.random.permutation(13) # from 0 to 13, integer numbers list

array([ 2,  6, 12,  5,  4, 11,  8, 10,  1,  0,  9,  3,  7], dtype=int32)

In [43]:
arr = np.random.shuffle([3, 4])

In [47]:
arr = np.array([3, 4, 5])
np.random.shuffle(arr)

In [50]:
arr

array([4, 3, 5])

In [61]:
np.random.randint(1, 13) # integers removed, instead randint

3

In [112]:
np.random.standard_normal((2, 3))

array([[ 1.04164811, -0.87992963, -0.0068801 ],
       [ 0.41826806, -0.89486446,  1.14650931]])

In [102]:
np.random.binomial(0.9, 0.1)

0

In [110]:
np.random.normal([1, 8, 6])

array([1.65162333, 8.16341752, 6.80581712])

In [122]:
np.random.beta(4, 4)

0.5143787635974932

In [147]:
np.random.chisquare(1, 5)

array([0.25485653, 2.24887332, 0.99632514, 1.17895753, 0.02905427])

In [160]:
np.random.gamma((3, 7))

array([ 0.97478261, 14.15022045])

In [182]:
np.random.uniform((3, 5))

array([2.99656642, 2.0529895 ])